### ISSUE TITLE
Donation tracker integration

### ISSUE THREAD

**Issue by geoidesic** [geoidesic/foundryvtt-actor-studio#32]
1. [x] Check for `donation-tracker` module. If enabled, add game setting with button to open new application
2. [x] Add TJS application for this setting
3. [x] The first setting in the new application should be a checkbox to enable / disable donation-tracker integration.
4. [x] The application should read values from `game.membership.RANKS` and create a text field setting per RANK
5. [x] Each text field should contain a folder name, which will define which folders in a compendium contain content for that RANK. 
6. [x] Anything not in a folder, or in an unnamed folder need not be filtered by RANK
7. [x] When this is enabled, users of Actor Studio will have their content filtered by RANK where appropriate (i.e. from compendiums where the named folders exist).
